title: "EPAM Interview Prep"
description: "Comprehensive preparation material for EPAM and BigTech backend interviews"
baseurl: "/epam-interview-prep"
theme: minima

# SEO & Social
author: "Davronbek Boltayev"
lang: en-US
email: davronbekboltyev@gmail.com
url: "https://firdavsdev.github.io/epam-interview-prep"
github_username: firdavsDev
linkedin: davronbek-boltayev

# Theme config
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/firdavsDev" }
    - {
        platform: linkedin,
        user_url: "https://linkedin.com/in/davronbek-boltayev",
      }
  header_pages:
    - index.md

# Markdown renderer
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Favicon
favicon: "/epam-interview-prep/favicon.ico"

# Default layout for pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: default

# Build exclusions
exclude:
  - README.md
  - CONTRIBUTORS.md
  - LICENSE
